### ISSUE TITLE
Prev/Next should be disabled on first/last page

### ISSUE THREAD

**Issue by jcubic** [damiisdandy/use-pagination#1]
The demo shows that hover effect over prev/next when there is no prev next so it looks that you can click on it but it does do nothing.

The next/prev arrow should be hidden or don't have a hover effect, best if it has a class that can be styled.

**Comment by damiisdandy** [comment]
I've also just added the disabled functionality [here](https://github.com/damiisdandy/use-pagination/commit/1bae6900fc67a704f52c091b4a220d9d4a3605fe#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2) for the sake of completion.
