### ISSUE TITLE
Support larger number of pages

### ISSUE THREAD

**Issue by jcubic** [damiisdandy/use-pagination#2]
You should be able to have 10 items per page and 1000 pages for the library to be fully functional.

You should control a number of pages display at once. it should use `...` markers to indicate that there are more pages in between. There are 3 cases:
* page at the beginning it should show `...` at the end, before the last item that shows the last page.
* page in the middle it should show `...` at start and end, after first and before last
* page at the end it should show `...` at the start after the first item.

**Comment by damiisdandy** [comment]
As mentioned this [closed issue](https://github.com/damiisdandy/use-pagination/issues/1), this repo simply just demonstrates the `usePagination()` hook and not how you render the navigation buttons, you can implement this yourself with the return values of the `usePagination()` hook. If you'd like me to convert this to a full-fledge library that also returns a component of navigation links, share this repo and get it to 30 stars, Thank you  💙
